
import { Post } from '../types';

const posts: Post[] = [
  {
    id: '1',
    title: 'The Future of UI/UX Design with AI',
    excerpt: 'Explore how artificial intelligence is revolutionizing the way we design user interfaces and experiences, from automated design systems to personalized user journeys.',
    content: `
      <p class="mb-4">Artificial intelligence is no longer a futuristic concept; it's a present-day tool that is reshaping industries, and UI/UX design is no exception. As we venture deeper into the 21st century, AI is set to become an indispensable partner for designers, augmenting their creativity and streamlining their workflows.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Generative Design and AI</h3>
      <p class="mb-4">One of the most exciting frontiers is generative design. AI algorithms can now generate thousands of design variations in minutes, based on a set of predefined parameters. This allows designers to explore a vast design space that would be impossible to cover manually. Tools like Adobe Sensei are already integrating these capabilities, helping create everything from logos to full website layouts.</p>
      <p class="mb-4">This doesn't mean designers will be replaced. Instead, their role will shift from pixel-pushing to curating and refining the best options generated by the AI, focusing on strategic thinking and user empathy.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"AI will be the most powerful tool in a designer's toolkit. The challenge is not whether to adopt it, but how to master it."</blockquote>
      <h3 class="text-2xl font-bold mt-6 mb-3">Personalization at Scale</h3>
      <p class="mb-4">AI excels at analyzing vast amounts of user data to identify patterns and preferences. This enables hyper-personalization of user experiences. Imagine a website that dynamically adjusts its layout, content, and color scheme based on your past behavior, location, and even the time of day. Netflix and Spotify are pioneers in this area with their recommendation engines, but this is just the tip of the iceberg.</p>
      <p>The future of UI is an interface that feels uniquely tailored to each individual user, creating a more engaging and intuitive interaction.</p>
    `,
    author: 'Jane Doe',
    authorAvatar: 'https://i.pravatar.cc/150?u=jane_doe',
    date: 'October 26, 2023',
    readTime: 7,
    tags: ['AI', 'UI/UX', 'Design', 'Future'],
    imageUrl: 'https://picsum.photos/seed/ai-future/1200/800',
  },
  {
    id: '2',
    title: 'Mastering State Management in Modern React',
    excerpt: 'A deep dive into the evolution of state management in React, from prop drilling to Context API, and the rise of libraries like Redux, Zustand, and Jotai.',
    content: `
      <p class="mb-4">State management has always been a central challenge in building complex React applications. As applications grow, so does the complexity of sharing data between components. Let's trace the journey of state management and explore the modern solutions available today.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">The Old Days: Prop Drilling</h3>
      <p class="mb-4">Initially, the only way to share state was by passing props down through the component tree. This approach, known as "prop drilling," quickly becomes cumbersome and leads to tightly coupled components and maintenance nightmares.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">React's Built-in Solutions: Context API</h3>
      <p class="mb-4">The introduction of the Context API was a game-changer. It provided a native way to share state globally without prop drilling. Combined with the <code>useReducer</code> hook, it offers a powerful solution for managing complex state logic within React itself, reducing the need for external libraries for many use cases.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"Context API made global state management accessible without the boilerplate of Redux."</blockquote>
      <h3 class="text-2xl font-bold mt-6 mb-3">The Rise of Modern Libraries</h3>
      <p class="mb-4">While Context is great, dedicated state management libraries still have their place. <strong>Redux</strong> remains a robust choice for large-scale applications with predictable state mutations. However, newer, more lightweight libraries like <strong>Zustand</strong> and <strong>Jotai</strong> have gained immense popularity. They offer a simpler API, less boilerplate, and a more "React-ish" feel, making them excellent choices for projects of all sizes.</p>
    `,
    author: 'John Smith',
    authorAvatar: 'https://i.pravatar.cc/150?u=john_smith',
    date: 'October 22, 2023',
    readTime: 9,
    tags: ['React', 'State Management', 'Web Development'],
    imageUrl: 'https://picsum.photos/seed/react-state/1200/800',
  },
  {
    id: '3',
    title: 'Building Accessible Web Applications: A Guide',
    excerpt: 'Accessibility (a11y) is not just a feature, it\'s a fundamental requirement. This guide covers the key principles and practical tips for building inclusive web apps.',
    content: `
      <p class="mb-4">Web accessibility (often abbreviated as a11y) is the practice of ensuring that your websites and applications are usable by everyone, regardless of their abilities or disabilities. It's not just a legal requirement in many places, but a moral and ethical one.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">The Four Principles of WCAG</h3>
      <p class="mb-4">The Web Content Accessibility Guidelines (WCAG) are built around four core principles, often remembered by the acronym POUR:</p>
      <ul class="list-disc list-inside mb-4 pl-4 space-y-2">
        <li><strong>Perceivable:</strong> Users must be able to perceive the information being presented. This means providing text alternatives for non-text content, like alt text for images.</li>
        <li><strong>Operable:</strong> Users must be able to operate the interface. This includes making all functionality available from a keyboard.</li>
        <li><strong>Understandable:</strong> Information and the operation of the user interface must be understandable. This involves using clear language and providing predictable navigation.</li>
        <li><strong>Robust:</strong> Content must be robust enough that it can be interpreted reliably by a wide variety of user agents, including assistive technologies.</li>
      </ul>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"The power of the Web is in its universality. Access by everyone regardless of disability is an essential aspect." - Tim Berners-Lee</blockquote>
      <h3 class="text-2xl font-bold mt-6 mb-3">Practical Tips for React Developers</h3>
      <p class="mb-4">As a developer, you can make a huge impact:</p>
      <ul class="list-disc list-inside mb-4 pl-4 space-y-2">
        <li><strong>Use Semantic HTML:</strong> Use <code>&lt;nav&gt;</code>, <code>&lt;main&gt;</code>, <code>&lt;button&gt;</code>, etc., appropriately. They come with built-in accessibility features.</li>
        <li><strong>Manage Focus:</strong> Ensure focus is managed correctly, especially in dynamic applications and modals.</li>
        <li><strong>Use ARIA attributes wisely:</strong> Use ARIA (Accessible Rich Internet Applications) attributes to enhance accessibility where semantic HTML isn't enough.</li>
        <li><strong>Test with Screen Readers:</strong> Regularly test your app with tools like VoiceOver (macOS) or NVDA (Windows) to understand how users with visual impairments experience your site.</li>
      </ul>
    `,
    author: 'Alice Johnson',
    authorAvatar: 'https://i.pravatar.cc/150?u=alice_johnson',
    date: 'October 15, 2023',
    readTime: 6,
    tags: ['Accessibility', 'Web Development', 'a11y'],
    imageUrl: 'https://picsum.photos/seed/accessibility/1200/800',
  },
  {
    id: '4',
    title: 'The Unstoppable Rise of Tailwind CSS',
    excerpt: 'Why has Tailwind CSS, a utility-first CSS framework, taken the web development world by storm? We explore its philosophy, benefits, and why you should consider it for your next project.',
    content: `
      <p class="mb-4">In a world of component-based frameworks like React and Vue, the way we write CSS has been evolving. Tailwind CSS has emerged as a front-runner, offering a radically different, yet incredibly effective, approach to styling.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">What is Utility-First CSS?</h3>
      <p class="mb-4">Instead of writing CSS classes based on components (e.g., <code>.card</code>, <code>.button</code>), Tailwind provides low-level utility classes (e.g., <code>.bg-blue-500</code>, <code>.p-4</code>, <code>.flex</code>). You build complex components by composing these utilities directly in your HTML.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"Tailwind encourages you to build custom designs without ever leaving your HTML."</blockquote>
      <h3 class="text-2xl font-bold mt-6 mb-3">Key Advantages</h3>
      <ul class="list-disc list-inside mb-4 pl-4 space-y-2">
        <li><strong>Rapid Prototyping:</strong> You can style elements incredibly fast without context-switching between your markup and stylesheets.</li>
        <li><strong>No More Naming Things:</strong> Say goodbye to agonizing over class names like <code>.user-profile-card-header-title</code>.</li>
        <li><strong>Consistency:</strong> The built-in design system (spacing, colors, etc.) ensures consistency across your entire application.</li>
        <li><strong>Performance:</strong> Tailwind automatically purges unused CSS in production, resulting in incredibly small bundle sizes.</li>
      </ul>
      <p>While the initial learning curve might involve getting used to what some call "ugly markup," the productivity gains and maintainability benefits are often a massive win for development teams.</p>
    `,
    author: 'Chris Lee',
    authorAvatar: 'https://i.pravatar.cc/150?u=chris_lee',
    date: 'September 30, 2023',
    readTime: 8,
    tags: ['CSS', 'TailwindCSS', 'Frontend'],
    imageUrl: 'https://picsum.photos/seed/tailwind-css/1200/800',
  },
  {
    id: '5',
    title: 'TypeScript Best Practices for Large-Scale Applications',
    excerpt: 'Learn essential TypeScript patterns and practices that will help you build maintainable, scalable applications with confidence and type safety.',
    content: `
      <p class="mb-4">TypeScript has become the de facto standard for building large-scale JavaScript applications. Its static type system catches errors at compile time, improves code documentation, and enhances developer experience. However, to truly harness its power, you need to follow best practices.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Strict Configuration</h3>
      <p class="mb-4">Always enable strict mode in your <code>tsconfig.json</code>. This includes <code>noImplicitAny</code>, <code>strictNullChecks</code>, and other strict flags that catch common errors and force you to be explicit about your types.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Type Guards and Narrowing</h3>
      <p class="mb-4">Use type guards to safely narrow union types. This is especially important when working with data from APIs or user input where you can't guarantee the shape of the data.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"TypeScript's type system is your friend. The stricter you are, the more it helps you."</blockquote>
      <h3 class="text-2xl font-bold mt-6 mb-3">Utility Types</h3>
      <p class="mb-4">Master TypeScript's built-in utility types like <code>Partial</code>, <code>Pick</code>, <code>Omit</code>, and <code>Record</code>. These can help you create flexible, reusable type definitions without repeating yourself.</p>
      <p>Remember, TypeScript is not just about adding types to JavaScript—it's about leveraging the type system to write better, more maintainable code.</p>
    `,
    author: 'Sarah Chen',
    authorAvatar: 'https://i.pravatar.cc/150?u=sarah_chen',
    date: 'November 12, 2023',
    readTime: 10,
    tags: ['TypeScript', 'JavaScript', 'Best Practices', 'Web Development'],
    imageUrl: 'https://picsum.photos/seed/typescript/1200/800',
  },
  {
    id: '6',
    title: 'The Art of Micro-Interactions in Web Design',
    excerpt: 'Discover how subtle animations and micro-interactions can dramatically improve user experience and make your web applications feel more alive and engaging.',
    content: `
      <p class="mb-4">Micro-interactions are the small, subtle animations and feedback mechanisms that occur when users interact with your interface. They might seem insignificant, but they play a crucial role in creating delightful user experiences.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">What Are Micro-Interactions?</h3>
      <p class="mb-4">Think of the heart animation when you like a post on Instagram, the pull-to-refresh gesture on mobile apps, or the subtle hover effects on buttons. These small details provide feedback, guide users, and add personality to your interface.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">The Four Parts of Micro-Interactions</h3>
      <ul class="list-disc list-inside mb-4 pl-4 space-y-2">
        <li><strong>Trigger:</strong> What initiates the micro-interaction (user action or system event)</li>
        <li><strong>Rules:</strong> What happens during the interaction</li>
        <li><strong>Feedback:</strong> How users know what's happening</li>
        <li><strong>Loops & Modes:</strong> The meta-rules that govern the interaction</li>
      </ul>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"The best micro-interactions are invisible until they're not there."</blockquote>
      <p class="mb-4">When implementing micro-interactions, remember that less is more. They should enhance the experience, not distract from it. Use them to provide feedback, guide attention, and create a sense of direct manipulation.</p>
    `,
    author: 'David Park',
    authorAvatar: 'https://i.pravatar.cc/150?u=david_park',
    date: 'November 8, 2023',
    readTime: 5,
    tags: ['Design', 'UX', 'Animation', 'Micro-interactions'],
    imageUrl: 'https://picsum.photos/seed/microinteractions/1200/800',
  },
  {
    id: '7',
    title: 'Building Performant React Applications: A Complete Guide',
    excerpt: 'Learn advanced techniques for optimizing React applications, from code splitting and lazy loading to memoization and virtual scrolling.',
    content: `
      <p class="mb-4">Performance is crucial for user experience. Slow applications lead to frustrated users and lost business. In this comprehensive guide, we'll explore various techniques to optimize React applications for maximum performance.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Code Splitting and Lazy Loading</h3>
      <p class="mb-4">Use React's <code>lazy()</code> function and <code>Suspense</code> to split your code and load components only when needed. This reduces the initial bundle size and improves load times.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Memoization Strategies</h3>
      <p class="mb-4">Leverage <code>React.memo</code>, <code>useMemo</code>, and <code>useCallback</code> to prevent unnecessary re-renders. However, use them judiciously—premature optimization can hurt performance.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"Premature optimization is the root of all evil, but knowing when to optimize is the art of engineering."</blockquote>
      <p>Remember to measure performance before and after optimizations. Use React DevTools Profiler to identify bottlenecks and validate your improvements.</p>
    `,
    author: 'Michael Rodriguez',
    authorAvatar: 'https://i.pravatar.cc/150?u=michael_rodriguez',
    date: 'November 5, 2023',
    readTime: 12,
    tags: ['React', 'Performance', 'Optimization', 'Web Development'],
    imageUrl: 'https://picsum.photos/seed/react-performance/1200/800',
  },
  {
    id: '8',
    title: 'CSS Grid vs Flexbox: When to Use Which',
    excerpt: 'Master the art of modern CSS layouts by understanding the strengths and ideal use cases for both CSS Grid and Flexbox in your web projects.',
    content: `
      <p class="mb-4">CSS Grid and Flexbox are both powerful layout systems, but they serve different purposes. Understanding when to use each one will make you a more effective developer and help you create better layouts.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">Flexbox: One-Dimensional Layouts</h3>
      <p class="mb-4">Flexbox excels at distributing space and aligning items in a single dimension—either horizontally or vertically. It's perfect for navigation bars, button groups, and centering content.</p>
      <h3 class="text-2xl font-bold mt-6 mb-3">CSS Grid: Two-Dimensional Layouts</h3>
      <p class="mb-4">CSS Grid is designed for two-dimensional layouts where you need to control both rows and columns simultaneously. It's ideal for page layouts, card grids, and complex designs.</p>
      <blockquote class="border-l-4 border-slate-300 pl-4 italic my-6">"Use Flexbox for components, use Grid for layouts."</blockquote>
      <p>The best approach is often to use both together—Grid for the overall page structure and Flexbox for individual components within that structure.</p>
    `,
    author: 'Lisa Wang',
    authorAvatar: 'https://i.pravatar.cc/150?u=lisa_wang',
    date: 'October 28, 2023',
    readTime: 7,
    tags: ['CSS', 'Grid', 'Flexbox', 'Layout', 'Frontend'],
    imageUrl: 'https://picsum.photos/seed/css-grid-flexbox/1200/800',
  },
];

export const getPosts = (): Promise<Post[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(posts);
    }, 500); // Simulate network delay
  });
};

export const getPostById = (id: string): Promise<Post | undefined> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(posts.find((post) => post.id === id));
    }, 300); // Simulate network delay
  });
};
